In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
class discriminator(nn.Module):
    def __init__(self, in_features):
        super().__init__()
        self.disc = nn.Sequential(
            nn.Linear(in_features,64),
            nn.LeakyReLU(.01),
            nn.Linear(64, 1),
            nn.Sigmoid(),
        )

    def forward(self, x):
        return self.disc(x)
    
class generator(nn.Module):
    def __init__(self, n_dim, io_dim):
        super().__init__()
        self.gen = nn.Sequential(
            nn.Linear(n_dim,64),
            nn.LeakyReLU(.01),
            nn.Linear(64, io_dim),
        )

    def forward(self, x):
        return self.gen(x)

n_dim = 3 #noise dimension.
io_dim = 20 #generator output and disc input dimension.
lr = 3e-4
num_epoch = 1000
num_exp = 50
#batch = 100

disc = discriminator(io_dim)
gen = generator(n_dim, io_dim)

opt_disc = optim.Adam(disc.parameters(), lr=lr)
opt_gen = optim.Adam(gen.parameters(), lr=lr)
criterion = nn.BCELoss()

data = torch.normal(2,1,(1,io_dim))
fixed = torch.randint(0,2,(1,n_dim))
fixed_noise = fixed.float()

z= np.zeros(num_exp*io_dim)
for ep in range(num_exp):

    for epoch in range(1000):
        for batch in range(100):

            ##Training discriminator
            noise = torch.randint(0,2,(1,n_dim))
            noise_f = noise.float()
            fake = gen(noise_f)
            disc_real = disc(data)
            lossD_real = criterion(disc_real, torch.ones_like(disc_real))
            disc_fake = disc(fake)
            lossD_fake = criterion(disc_fake, torch.zeros_like(disc_fake))
            lossD = (lossD_real + lossD_fake) / 2
            disc.zero_grad()
            lossD.backward(retain_graph=True)
            opt_disc.step()


            ##Training generator
            output = disc(fake)
            lossG = criterion(output, torch.ones_like(output))
            gen.zero_grad()
            lossG.backward()
            opt_gen.step()

        generated_samples = gen(noise_f)
        

        for ep1 in range(io_dim):
            z[io_dim*ep + ep1] = generated_samples[0,ep1].item()


In [ ]:
m=generated_samples
print(torch.mean(m))
print(torch.std(m))

In [ ]:
z

In [ ]:
from scipy.stats.kde import gaussian_kde
density = gaussian_kde(z)
xs = np.linspace(-3,7,len(z))
plt.plot(xs,density(xs))
#plt.hist(K1,density=True)
#matplotlib.pyplot.title('marginal distribution of alpha1')
plt.ylabel('alpha1')
#plt.plot(K1,np.exp(-K3))
plt.show()
#statistics.mode(Kth_1)
a = (density(xs))
i = list(a).index(max(density(xs))) 
i
xs[i]

In [ ]:
data

In [ ]:
n = torch.randint(0,2,(1,3)).float()
gen(n)

In [ ]:
b=y.float()
v(b)

In [ ]:
z.shape

In [ ]:
print(type(z))
print(type(y))

In [3]:
y = torch.Tensor([[10,6,3]])
m = torch.distributions.dirichlet.Dirichlet(y)
z=m.sample()
data = torch.normal(2,1,(1,3))
print(data)
print(z)

tensor([[0.3205, 2.0439, 3.1458]])
tensor([[0.4806, 0.3957, 0.1238]])


In [44]:
class generator(nn.Module):
    def __init__(self, n_dim, io_dim):
        super().__init__()
        self.gen = nn.Sequential(
            nn.Linear(n_dim,64),
            nn.LeakyReLU(.01),
            nn.Linear(64, io_dim),
        )

    def forward(self, x):
        return self.gen(x)

In [45]:
gen = generator(3,3)
gen(z)

tensor([[-0.0635,  0.0355, -0.0295]], grad_fn=<AddmmBackward>)

In [ ]:
x